# Generated by Django 3.2.9 on 2021-11-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharma',
            fields=[
                ('local_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=100)),
                ('local_nombre', models.CharField(max_length=100)),
                ('comuna_nombre', models.CharField(max_length=100)),
                ('fk_localidad', models.CharField(max_length=100)),
                ('localidad_nombre', models.CharField(max_length=100)),
                ('local_direccion', models.CharField(max_length=100)),
                ('funcionamiento_hora_apertura', models.CharField(max_length=100)),
                ('funcionamiento_hora_cierre', models.CharField(max_length=100)),
                ('local_telefono', models.CharField(max_length=100)),
                ('local_lat', models.CharField(max_length=100)),
                ('local_lng', models.CharField(max_length=100)),
                ('funcionamiento_dia', models.CharField(max_length=100)),
                ('fk_region', models.CharField(max_length=100)),
                ('fk_comuna', models.CharField(max_length=100)),
            ],
        ),
    ]
