# Generated by Django 3.2.9 on 2021-11-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pharma',
        ),
    ]
